name: Build typst resume

on: push

permissions:
  contents: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: typst-community/setup-typst@v5
      - run: typst compile main.typ resume.pdf

      - name: Generate tag
        id: tag
        run: |
          TAG="$(date +'%Y.%m.%d')"
          echo "tag=$TAG >> $GITHUB_OUTPUT"

      - name: Create git tag
        run: |
          git tag "${{ steps.tag.outputs.tag }}"
          git push origin "${{ steps.tag.outputs.tag }}"

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v6
      #   with:
      #     name: resume
      #     path: resume.pdf

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: resume.pdf
